?start: statement

?statement: ontology

ontology: "ONTOLOGY" ONTOLOGY_TYPE ontology_node

label:          CNAME
ontology_node:  "(:" label [properties] ")"
pair:           property_key ":" ESCAPED_STRING
properties:     "{" [pair ("," pair)*] "}"
property_key:   CNAME | ESCAPED_KEY

ESCAPED_KEY:    /`[^`]+`/
ONTOLOGY_TYPE:  "object" | "relationship" | "property"

%import common.CNAME
%import common.ESCAPED_STRING
%import common.WS
%ignore WS